### ISSUE TITLE
Can't dump privkeys

### ISSUE THREAD

**Issue by iwoolf** [langerhans/dogecoinj-new#20] opened 2021-01-31 22:52 UTC
I have a wallet-protobuf, keys-backup-protobuf, and keys-backup-protobuf.79 files from a 2014 backup of my entire android phone. They were the working files, not an export, so they're not encrypted. I have tried importing the wallet in the Dogecoin app, failed. I tried encrypting the protobuf wallet, but the Dogecoinapp says "Wallet could not be restored. Could not decrypt bytes. Bad password?"

I downloaded dogecoinj, and it fails like this:
"./wallet-tool dump --wallet=wallet-protobuf --dump-privkeys
Failed to load wallet 'wallet-protobuf': Unknown network parameters ID org.dogecoin.production
org.bitcoinj.wallet.UnreadableWalletException: Unknown network parameters ID org.dogecoin.production
	at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:436)
	at org.bitcoinj.tools.WalletTool.main(WalletTool.java:332)"

How do I fix this please? I've spent many hours searching for advice, and haven't found any solutions. I'm not a developer.

**Comment by langerhans** [comment] 2021-02-01 07:51
Duplicate of #19

**Closed as completed by langerhans** 2021-02-01 07:51 UTC
